ebassi/graphene

src/graphene-box.c
src/graphene-private.h
src/graphene-vectors.c

Hi,
The recent updates to Graphene broke the build on Windows, which can be fixed with some rather simple updates.  I have made the necessary updates to the sources in my fork so that these issues could be remedied.
I will also try to come up with Visual Studio projects/NMake Makefiles to build the sources as soon as possible-sorry I did not have the time to look into Graphene lately due to work on other items.
p.s. Is it correct to assume that there is no intention to support Windows XP for this project, just to double-check (I couldn't check XP compatibility, as I don't normally run it, and I am all for dropping XP support in the GTK+ stack :) ), at least from a thread-safety perspective?
With blessings, thank you!

Fix build on Windows

---

src/graphene-alloc.c

This fixes build errors on Android:
graphene-alloc.c: In function 'graphene_aligned_alloc':
graphene-alloc.c:103:3: error: 'errno' undeclared (first use in this function)
errno = 0;

alloc: Include errno.h

---

src/Makefile.am
src/graphene.pc.in

This file is architecture dependent. To support multilib we need
to make sure multiple copies can coexist.

Install graphene-config.h in libdir

---

src/tests/graphene-test-compat.h
src/tests/triangle.c

When reading the API, I thought that u was on the ab axis and v on the ac axis. But it's the reverse. Is that normal?
Also, as the FIXME comment shows in the unit test, getting the barycoords of a 3D point _not_ in the triangle plane returns true (valid coords) nonetheless. Is that normal?

Add unit tests for graphene_triangle_get_barycoords()

---

src/tests/triangle.c

The function always returns a positive area. Signed areas can be useful
for some computations in computer graphics, but it is not present in
graphene.

tests: add unit test for graphene_triangle_get_area()

---

src/graphene-sphere.c

I know what is a translation, but it was not clear to me whether @point
referred to the new center coordinates, or the delta. It turns out that
it's the delta, as expected for a translation, but it's better to
explain it in the docs.

docs: improve doc of graphene_sphere_translate()

---

src/graphene-simd4x4f.h

Hi,
(Sorry, I forgot to post about this, which was an issue for a while...)
The current placement of GRAPHENE_VECTORCALL, which is expanded to __vectorcall on Visual Studio 2013 and later (for 32-bit builds) is actually breaking the build there.  That needs to be done after the return type.
With blessings, thank you!

graphene-simd4x4f.h: Fix x86 Builds on MSVC 2013 and Later

---

src/graphene-simd4f.h

Not sure why the missing semicolon didn't get caught before.

simd4f: Fix a compilation error

---

meson.build
src/meson.build

Fixes building graphene as a meson submodule
- meson: Fix library version and soversion
- meson: Do not use add_global_arguments but instead pass the args ourself

Fix building graphene as a meson submodule

---

src/graphene-matrix.c
src/graphene-simd4f.c

Part 2 of splitting PR #64 into two separate PRs.
The underlying ARM fast type that graphene_simd4f_get calls into requires
its inputs to be compile time constants. Passing the "col" argument in was
causing the build to fail.

Fixing build errors on ARM NEON.

---

meson.build
src/graphene-config.h.meson
src/meson.build

Hi,
This attempts to add proper support out-of-the box for building Graphene using Visual Studio, so that we can make use of it with Visual Studio builds of the upcoming GTK+-4.x (for GSK), as most of the code is ready for building and usage under Visual Studio 2008+ (!), but a build system that would support the MSVC toolchain is not yet in place.
As a result, updates are needed for the meson build files to support the toolchain properly, and a few minor changes are needed for the code so that things will work in the Visual Studio versions that we support for GTK+ (the code changes I will post later).  Note that on 32-bit builds, Visual Studio 2013 or later is required to enable SSE2 support due to x86/32-bit ABI limitations.
With blessings, thank you!

build: Allow proper build with Visual Studio out-of-the-box

---

src/config.h.meson
src/graphene-point.c
src/graphene-point3d.c
src/graphene-rect.c
src/graphene-size.c

Hi,
We have started to use C99-style struct initializers, which is support by Visual Studio 2013/2015, with one exception, that is, using them in initializing static variables and global constants, which will cause C2099 to be raised (initializer not a constant).  This might also affect other compilers as well.
Also, we need to update config.h.meson to define inline as __inline for pre-2013 Visual Studio as well, in addition to graphene-config.h.meson.  I am not sure whether meson has a mechanism for detecting the 'inline' definition for the compiler, so this is what I have for now.
With bessings, thank you!

Fix build of 1.5.1 on Visual Studio

---

meson.build
src/bench/graphene-bench-utils.c
src/bench/matrix.c
src/config.h.meson

Fixes #83 
MinGW also uses `_aligned_malloc()`, not just MSVC. Without this, we were just returning uninitialized memory since no other aligned allocator was available.
Also, use `G_GINT64_FORMAT` for printing `gint64` otherwise we get a segfault while printing.

meson: Detect and use _aligned_malloc on MinGW

---

meson.build
src/bench/matrix.c
src/graphene-alloc.c

Fixes https://github.com/ebassi/graphene/pull/84#discussion_r90875361
Both `stdlib.h` and `malloc.h` define it on MinGW but it's only defined by `malloc.h` on MSVC, so just use `malloc.h`.
There are more issues needed for MSVC support, but this should help.

Use malloc.h for _aligned_malloc instead of stdlib.h

---

.travis.yml
configure.ac
src/Makefile.am

> We cannot rely on a shebang line on different platforms.
>
> Fixes https://github.com/ebassi/graphene/issues/88 for autotools.
Addresses #88 again for autotools.
- invoke Python directly just like a3a959bc0e3dc8393ba57ce47afd8383cc8c845a
- I cannot get graphene to build with either autotools or meson yet, so I was not able to run the tests.
- None. The build will fail in the absence of Python however (perhaps with a meaningful error message, even)

autotools: Use Python to invoke identfilter.py

---

README.md

> This commit updates README.py with better tested documentation for the
> MSYS2 platform on Windows. Previously the instructions would fail because
> "automake" is not a package.
> 
> This commit also gets the user to select packages based on their intended
> target platform, a concept that matters on MSYS2 because each target
> has its own $PREFIX.
> 
> The docs were also out of date in that they did not cover meson.
--------------------------
- Update README.md as described in the commit message, quoted above.
- I have not been able to get it to build yet, so I have not investigated this.
- No change is expected because this is a docs-only commit.
- None proposed.

Update build docs for MSYS2

---

meson.build

Fixes #76.
- Cascading tests for the aligned malloc func as recommended by @nirbheek 
- Workaround for compilation on MSYS2: a hopefully temporary platform check
- Still cannot compile on Win32 (blocked by #88)
- None
----------------
As recommended by @nirbheek, only search for a single aligned memory
allocation function: https://github.com/ebassi/graphene/pull/86#issuecomment-264900534
The cascade of tests means we can exclude the ones for which MSYS2's
native mingw-w64 builtins and headers conspire to provide meson with a
dud test. Although it is still not clear that meson is doing the right
thing in this case (mesonbuild/meson#1083), we can work around the
failed build in graphene by excluding certain POSIXy cases on Windows. …

Use only one aligned alloc func, work around msys2

---

meson.build
src/meson.build
src/tests/meson.build

meson build files have been changed to include a variable with graphene string to be used instead of hard coded strings.
Fixes #101
- Changed the version number handling for generated files and directories in the meson build files.
- Before: ...
- After: ...
- ...

Updated meson build files to ease API version change.

---

src/meson.build

Apple's clang-9 (no idea what that maps to in clang's normal version) doesn't like an '=' in the version flags.
Fixes #...
- ...
- Before: ...
- After: ...
- ...

Fix Xcode-9 compile error

---

src/meson.build

This is required for using graphene as a subproject inside gtk+

Add gir and typelib to declare_dependency for subproject use

---

meson.build
src/graphene-box.c
src/graphene-config.h.meson
src/graphene-point3d.c
src/graphene-vectors.c

We're using a bunch of pre-processor symbols before checking if they are defined, which makes it hard to build Graphene if compiler flags like `-Wundef` are used.
Fixes #114

Check pre-processor symbols

---

src/graphene-box.c
src/graphene-private.h
src/graphene-vectors.c

partly fixes #118 
I haven't figured out the SSE related warning (seems to be a real warning, enabling SSE on 32bit seems to change ABI and things crash until rebuild)

Fix some MinGW warnings

---

.appveyor.yml
.appveyor/msvc.bat
.appveyor/msys2-pre.sh
.appveyor/msys2.sh

Context: https://github.com/ebassi/graphene/issues/114#issuecomment-379840661
The first commit moves the MSVC commands into a separate file, the second one adds MSYS2 support.
Sadly every build goes through all commands so you either have to do lots of ifs everywhere or move things to batch/shell files. And with batch files you have to do that goto stuff to get it to fail properly. But it seemed like less of a mess all in all.

appveyor: Add MSYS2 jobs

---

meson.build
src/meson.build

They were only added to extra_args which isn't used to build tests/benchmarks.
Add them to common_cflags instead.

meson: make sure simd related cflags are used for tests/benchmarks

---

meson.build
src/graphene-config.h.meson

SIMD implementations are terrible on 32bit IA for a variety of reasons:
- SSE2+ intrinsics are generally unsupported except on very old CPU
packages, and compilers are poorly optimized for those
- GCC vectorization builtins require a decent version of GCC to begin
with, and will likely work badly on 32 bit builds
- allocators on 32bit are not capable of aligning SIMD-based
structures, and no amount of trickery will allow them to work
properly.
If you're building Graphene for 32 bit you're much better served by
using the scalar fallback code; it may be slow, but at least it'll work
as expected.

Disable SIMD optimizations on 32bit Intel Architectures

---

src/graphene-matrix.c
src/graphene-simd4x4f.h
src/tests/graphene-test-compat.h
src/tests/matrix.c

The transformation of 2D and 3D points should take into account the W row of the matrix, unlike transformations of vec3 vectors.
Currently, the `graphene_matrix_transform_point()` implementation calls into the matrix/vec3 multiplication, which is wrong; the `graphene_matrix_point3d()` implementation correctly calls into the matrix/point3 multiplication.
Additionally, the documentation is less than clear as to which API is meant to ignore the W components of both the matrix and the vector, and which API is meant to take into account the W row of the matrix alone.
- Added a new unit to verify that matrix/point and matrix/point3d transformations are different than matrix/vec3 transformations.

Fix point transformation

---

src/bench/matrix.c

error C4244: 'function': conversion from 'int' to 'float', possible loss of data
`i` can't be float because it is also used as an array subscript
This is the only changed needed to have graphene build with msvc.

Fix implicit conversion error when compiling with MSVC

---

src/bench/graphene-bench-utils.c

`size_t` is `unsigned long int` which is a 32-bit integer on 32-bit Windows. The multiplication in `malloc()` below then evaluates to a 32-bit integer which the compiler complains about.
This is normally a warning, but since we use `-we4244` it's an error.
src/bench/graphene-bench-utils.c(175): error C4244: 'function': conversion from 'gint64' to 'size_t', possible loss of data`
The number of rounds will never exceed INT_MAX, so we can just use an int here.

bench: Fix MSVC build error on 32-bit Windows

---

src/graphene-macros.h

g-i recently lost the ability to infer the bool type without a stdbool include.
While this is about to be fixed in g-i (https://gitlab.gnome.org/GNOME/gobject-introspection/merge_requests/116)
I don't see a reason why we should hide this in the first place, so remove the ifdef guard.

build: don't hide the stdbool include from g-ir-scanner

---

meson.build

We use `#ifdef HAVE_INIT_ONCE` all over the place, and set10() will
unconditionally define the symbol, which means the check will always
succeed even if InitOnce and friends are not available.

build: Do not use set10() for InitOnce checks

---

src/graphene-simd4x4f.h
src/tests/matrix.c

Otherwise if b == res, the row vectors will be overwritten while they
are still being used.
In particular, this fixes graphene_matrix_multiply (a, b, b) being
broken.
A new test, matrix/mutliply-self has been added.
Fixes #...
- ...
- Before: ...
- After: ...
- ...

simd4x4f: Use an intermediate for multiplication

---

src/graphene-matrix.c
src/tests/matrix.c

This looks like a thinko, where && and || where confused leading to way
too many matrices being accepted as 2D when they shouldn't.
A new test, matrix/is-2d has been added.

 matrix: Fix boolean logic in graphene_matrix_to_2d()

---

src/graphene-matrix.c
src/tests/matrix.c

The code was extracting the 3rd row as perspective, not the 3rd column.
A new test interpolate-perspective has been added.

matrix: Fix interpolation of perspective matrices

---

doc/graphene-sections.txt
src/graphene-matrix.c
src/graphene-matrix.h
src/meson.build
src/tests/matrix.c

- add a `graphene_matrix_near()` function
- use `near()` to implement `graphene_matrix_equal()`
- add a byte-by-byte comparator for fast checks
- document all newly added API
- add a unit for the newly added API

Add equality operators for the matrix type

---

meson.build
src/meson.build

Fixes: separate issue not opened
- `library()` should use `darwin_versions` to set the dylib versioning on macOS.
- Before: no benchmarking was performed
- After:
- None

build: use darwin_versions

---

src/graphene-rect.h
src/tests/rect.c

All other similar types have this initializer, and it
is quite handy.
- Add `GRAPHENE_RECT_INIT_ZERO`
Benchmark results: 
*(Does not apply)*
- Add an extra check in `rect_init` test

rect: Add GRAPHENE_RECT_INIT_ZERO

---

.appveyor/msvc.bat
doc/graphene-sections.txt
meson.build
src/graphene-euler.c
src/graphene-euler.h
src/graphene-quaternion.c
src/tests/euler.c
src/tests/meson.build
src/tests/quaternion.c

Fixes #96 
Closes #150 
- reimplement the conversion between `graphene_euler_t`, `graphene_matrix_t`, and `graphene_quaternion_t`
- extensively document the conventions used by `graphene_euler_t`
- add more rotation orders to `graphene_euler_order_t`
- fix the equality operator for `graphene_quaternion_t`
- cherry pick the roundtrip test from #150 
- update the unit for `graphene_quaternion_t`

Reimplement Euler angles

---

doc/graphene-sections.txt
src/graphene-rect.c
src/graphene-rect.h
src/tests/rect.c

- Add function for computing the area of a rect
- Add function to compute the rounded extents
- Fix docstring for round function
- Add function to print rects
- Test for `graphene_rect_round`
- Test for `graphene_rect_get_area`
- Test for `graphene_rect_round_extents`
Not sure if changing the round function would have been better, but I'd say no, as these two roundings cover different cases (for example, we'd need to round the extents when we want to pass a fractional rect for damaging the area).

Rect rounding improvements

---

.appveyor/msys2-pre.sh
.appveyor/msys2.sh

error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.3.0-2' required by mingw-w64-i686-gcc-ada
:: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.3.0-2' required by mingw-w64-i686-gcc-objc
:: installing mingw-w64-x86_64-gcc (9.1.0-1) breaks dependency 'mingw-w64-x86_64-gcc=8.2.0-3' required by mingw-w64-x86_64-gcc-ada
:: installing mingw-w64-x86_64-gcc (9.1.0-1) breaks dependency 'mingw-w64-x86_64-gcc=8.2.0-3' required by mingw-w64-x86_64-gcc-objc

CI: work around msys2 toolchain upgrade issues on appveyor

---

meson.build
src/graphene-matrix.c
src/graphene-simd4f.c
src/graphene-simd4f.h
src/graphene-simd4x4f.h
src/graphene-triangle.c
src/graphene-vectors.c

Stop comparing floating point values for equality; it's not safe to do.
Fixes #134

Remove float equality comparisons

---

meson.build
src/graphene-simd4f.h

Fixes: #97, #147, #148 
- Properly detect ARM NEON support in the toolchain
- Change the implementation for `graphene_simd4f_cmp_*` on ARM NEON
- Remove the compiler warning raised when using the ARM NEON implementation
of `graphene_simd4f_t`
- None

Fix ARM NEON support

---

src/graphene-quaternion.c

As discussed in the "Invertin Quaternions" section in:
http://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/slerp/
We need to check if the dot product (i.e. cos(theta/2)) is
negative. If so, that means the rotation is > 180 degrees and
we should invert the rotation so as to take the shortest path.
Without this rotation animations in gthree get really weird when you
pass 360 degrees. I.e. interpolation is slow clockwise until 360
deg, where it switches to a very fast counter-clockwise rotation only
to then continue the slow clockwise rotation.

graphene_quaternion_slerp: Always use the shortest path

---

src/graphene-matrix.c

It's tripping -Wunused on Clang (though not on GCC).
Fixes: #159

Remove unused function

---

doc/graphene-sections.txt
src/graphene-quaternion.c
src/graphene-quaternion.h

The operators coverage for `graphene_quaternion_t` is a bit low. As the fields in the quaternion structure are private, in order to implement common operations, like adding, multiplying, and scaling, you'd have to convert a quaternion into a vec4, operate on the vec4, and then turn the vec4 back into a quaternion. This is not really efficient, and could be easily solved by providing an actual API.
- Add `graphene_quaternion_add()`
- Add `graphene_quaternion_multiply()`
- Add `graphene_quaternion_scale()`

Add quaternion operators

---

doc/graphene-sections.txt
src/graphene-vec2.h
src/graphene-vec3.h
src/graphene-vec4.h
src/graphene-vectors.c

We have lerp() for every other vector-like type, including the SIMD
implementation, but we don't have one for the 2, 3, and 4-component
vector type wrappers.
- Add `graphene_vec2_interpolate()`
- Add `graphene_vec3_interpolate()`
- Add `graphene_vec4_interpolate()`

Add lerp operator for vector types

---

src/graphene-matrix.c

We can't use graphene_matrix_transform_vec3() to transform the origin
because we need to point to respect transformations (but not the
directions, so we can use vec3 there instead of reconstructing
the direction).
Fixes #...
- ...
- Before: ...
- After: ...
- ...

Fix graphene_ray_transform

---

doc/graphene-sections.txt
include/graphene-matrix.h
src/graphene-matrix.c

- Add `graphene_matrix_decompose()`

Matrix decompose

---

doc/graphene-sections.txt
include/graphene-ray.h
include/graphene-triangle.h
meson.build
src/graphene-matrix.c
src/graphene-ray.c
src/graphene-triangle.c
tests/ray.c
tests/triangle.c

Gthree has some in tree functionality that really belongs to Graphene.
- add `graphene_triangle_init_from_float()` initializer; this is useful for buffer objects with lots of triangles stored as vectors of floating point values
- add intersection methods for `graphene_ray_t`; this is used for hit testing objects like spheres, boxes, and triangles
- add `graphene_triangle_get_uv()`

Last minute API additions for Gthree

---

meson.build

The compiler warning C4819 (encoding related warning) is a trivial
thing on non-English locale system. Instead of error out,
explicitly specify encoding as "utf-8".

meson: Don't error with MSVC C4819 warning

---

src/graphene-matrix.c

If we're calling accessors functions on the same graphene_rect_t
multiple times, we end up normalizing the same rectangle. Let's do this
once at the start, and call the accessors on the normalized rectangle to
avoid tripping the normalization code paths.

Normalize input rectangles just once

---

include/graphene-config.h.meson
meson.build

Hi,
This updates the build for Visual Studio builds, as follows:
*  Support Visual Studio 2013 builds better-re-enable erroring out on C4819 when /utf-8 (a Visual Studio 2015+ feature) is not supported, to avoid mis-compilations, and let people know that it is actually possible to build Graphene as-is with Visual Studio 2013, but at the cost of needing to explicitly disable building and running the tests.
*  Disable SSE2 builds for all 32-bit x86 Visual Studio builds.  This is because although Visual Studio 2017 and 2019 improved on the __vectorcall calling convention (ABI), that needs to be used for 32-bit x86 builds, which is enough for running Graphene itself with the test programs, but this proved to be not enough to run more involved programs, such as GTK master.  Note that x64 …

Few fixes for Visual Studio builds

---

src/meson.build

Expose a separate variable for graphene-gobject for subproject usage
support, so the superproject and sibling subprojects can check for this
directly as part of the `dependency()` `fallback:` logic instead of having to
poke at the `build_gobject` subproject variable. This mirrors the pkg-config
lookup logic where we have a dedicated .pc file for graphene-gobject as well.
If gobject support was disabled the variable will be set to a `not-found` dep.

meson: expose graphene_gobject_dep variable for graphene-gobject

---

meson.build

Makes graphene find gobject in a gst-build on Windows scenario.

meson: pick up gobject from a subproject fallback as well

---

tests/gen-installed-test.py

The GNOME installed tests system expects the test output to be TAP:
"The key Output (if specified) can only take one value at present, which is TAP. This specifies that the test outputs Test Anything Protocol."
(https://wiki.gnome.org/Initiatives/GnomeGoals/InstalledTests)
Export MUTEST_OUTPUT=tap so this is the case.
Fixes #...
- ...
- Before: ...
- After: ...
- ...

tests: installed tests should use TAP

---

meson.build

`get_option('buildtype')` will return `'custom'` for most combinations
of `-Doptimization` and `-Ddebug`, but those two will always be set
correctly if only `-Dbuildtype` is set. So we should look at those
options directly.
For the two-way mapping between `buildtype` and `optimization` + `debug`, see this table:
https://mesonbuild.com/Builtin-options.html#build-type-options
Same change as glib: https://gitlab.gnome.org/GNOME/glib/merge_requests/1433

meson: Fix check for builtype arguments

---

include/graphene-simd4x4f.h

graphene_matrix_init_look_at() currently breaks badly in the case
where the given point is either the same as the eye, or in "up" direction
from the eye.
The exact definition of look_at() kinda breaks down in this situation,
but this is the behaviour three.js uses, and its better than nothing.

matrix_init_look_at: Handle corner cases better

---

src/graphene-euler.c

We have a bunch of aliases, so we need to ensure that we're using the
appropriate graphene_euler_order_t value, especially when performing
conversions to and from matrices.

Always convert the passed Euler order to the real one

---

src/graphene-euler.c

The euler_to_matrix and matrix_to_euler code is based on:
https://github.com/matthew-brett/transforms3d/blob/master/transforms3d/euler.py
This is num-py and has the same row-major matrixes like graphene. However
that code is based on column vectors being multiplied with the matrix on
the left:
> This module implements intrinsic and extrinsic axes, with standard conventions
> for axes `i`, `j`, `k`.  We assume that the matrix should be applied on the
> left of the vector, and right-handed coordinate systems.  To get the matrix to
> apply on the right of the vector, you need the transpose of the matrix we
> supply here, by the matrix transpose rule: $(M . V)^T = V^T M^T$.
To do the transpose we just change the matrix indexing macro (M) to swap
the row/column.

Euler: Fix matrix orientation in euler matrix (de)composition

---

include/graphene-config.h.meson
include/graphene-simd4f.h
include/graphene-simd4x4f.h
meson.build
src/graphene-ray.c

Hi,
This attempts to add support for building Graphene with ARM NEON intrinsics for Visual Studio ARM64 builds, which is introduced with Visual Studio 2017 15.9.x.  This is done in a way like the previous work on the SSE intrinsics for Visual Studio, as there is no extension available that can alleviate us from using a `static inline` function when calling the ARM NEON intrinsics.
This involves:
*  Skip the checks for the presence of the ARM EABI macros and the ARM NEON macros, since those macros are done in a GCC-specific way and are not present (but it seems that Visual Studio offer the functionality that are demanded/offered by those macros).  The test code for ARM NEON intrinsics do compile as a result.  Check for `_M_ARM64` in graphene-config.h.meson as well when checking to see …

ARM NEON: Add support for Visual Studio ARM64 builds

---

meson.build
src/meson.build
tests/gen-installed-test.py
tests/meson.build

We depend on a new enough version of Meson, so we can drop the old "python3" module, and use the appropriate "python" module API instead.

Drop deprecated "python3" module

---

src/graphene-box.c
tests/box.c

Fixes #201 
The old logic did essentially:
```
(min.x >= max.x && min.y >= max.y && min.z >= max.z)
```
which for a pair of non-intersecting boxes that differ in only one or two
dimensions will return false when we need it to return true (meaning there
is no intersection). What we really need is:
```
(min.x > max.x || min.y > max.y || min.z > max.z)
```
which can be rewritten as:
```
!(min.x <= max.x && min.y <= max.y && min.z <= max.z)
```

Fix graphene_box_intersection for non-intersecting boxes.

---

meson.build

Now SSE2 is enabled for 32-bit x86 by default (with recent GCC).  It's
causing issues such as https://gitlab.gnome.org/GNOME/gtk/-/issues/3497.

meson: only enable SSE2 on x86_64

---

include/graphene-macros.h
include/graphene-matrix.h
include/graphene-simd4f.h
include/graphene-vec2.h
include/graphene-vec3.h
include/graphene-vec4.h

Instead of relying on GCC accepting the same notation as MSVC.

Use the appropriate notation for alignment attributes

---

README.md
meson.build
meson_options.txt

This copies the same logic as in GTK+. A yielding feature option has the
advantage that if introspection is disabled in GTK and graphene is built
as subproject it will inherit the value from GTK main project.

meson: Change introspection option to yielding feature

---

include/graphene-config.h.meson
tests/introspection.py
tests/meson.build

Exposing the various #mesondefine'd constants results in the GIR XML
unnecessarily varying between architectures.
Conversely, GObject-Introspection's rather simplistic cpp parser
thinks GRAPHENE_SIMD_S is always defined to "sse", even on
architectures where it should not be.
Introspected code is not going to be able to use SIMD anyway, so this
doesn't seem to have any value.
Resolves: https://github.com/ebassi/graphene/issues/211
---
Not tested yet, but hopefully fixes #211.
- Wrap more of graphene-config.h in `#ifndef __GI_SCANNER__`
- not benchmarked
- Add a smoke-test for GObject-Introspection using PyGI

graphene-config: Hide SIMD implementation from GObject-Introspection

---

src/graphene-ray.c
tests/ray.c

The formula used to calculate the inverse of the direction vector
doesn't handle the direction vector aligning with an axis. Depending on
the SIMD (or not SIMD) implementation used, a axis aligned vector would
either remain the same, or e.g. end up with NaN components messing up
any future calculations.
Fixing the math to handle this is non-trivial, so for now work around
this by nudging the direction vector slightly off axis so that it has a
better hand of hitting the right box even when the direction is axis
aligned.
Closes: #214
Fixes #...
- ...
- Before: ...
- After: ...
- ...

ray: Nudge ray direction of axis when intersecting

---

src/graphene-private.h
src/graphene-ray.c

Avoids the #ifdef forest and code duplication resulting from it.
There was mismatch in the two code paths, see [1] and [2], and this
commit avoids repeating the same mistake.
[1] https://github.com/ebassi/graphene/issues/223
[2] https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3976
Fixes #223

ray: simplify nan checking by creating a macro.

---

tests/meson.build

Fixes installed-test. The instrospection.py file was not installed which made the corresponding test fail to run.

Fix installation of the introspection.py file for installed-tests

---

include/graphene-config.h.meson
meson.build

I actually don't have the hardware to test this, but in my QEMU user emulated environment it seems to allow AArch64 to use the NEON code-paths.
NEON for AArch64 has been supposedly enabled on Windows builds since https://github.com/ebassi/graphene/commit/29f9eb0245eac3e5c52ae9582984ae0f0d992553, but remained disabled on Linux builds.

Enable NEON for AArch64 on Linux

---

tests/ray.c

This test was split out from #224 which was fixed differently but without a test.

Add test for ray/box intersection based picking

---

meson.build

the previous behavior only ever enabled gcc vectors on x86_64
this results in a massive performance improvement in gnome 40 on ppc64le

meson: fix gcc vector 64-bit check

---

include/graphene-simd4f.h

Commit 8e5c25109898fa4894df810a546b26c387eaae93 introduced some pragmas, however those unintentionally change the types of the macros, as the diagnostic pop pragma becomes the last statement and the type of the expression becomes void.

Fix various broken macros when using GCC extension vectors

---

include/graphene-config.h.meson
meson.build

Hi,
From the commit message:
<i>On Visual Studio 2017, it is unfortunate that it does not allow us to include arm_neon.h directly for ARM64 builds, so we must include arm64_neon.h instead.</i>
<i>Interestingly, Visual Studio 2019 can include arm_neon.h directly for ARM64 builds, which will in turn include arm64_neon.h</i>
<i>Fix the Visual Studio 2017 ARM64 build by:</i>
*  <i>Updating the check program to include arm64_neon.h when building with Visual Studio 2017 for ARM64.</i>
*  <i>Use macros in graphene-config.h.meson so that we include the right header depending on the compiler being used when building for ARM64.</i>
With blessings, thank you!

build: Fix ARM64 (aarch64) builds on Visual Studio 2017

---

meson.build

Enable IEEE 754 with clang & gcc without running test. We may want to
add an extra option if necessary.

build-sys: do not cc.run() on cross-compiling

---

src/graphene-gobject.c

The `volatile` modifier got dropped from GLib.

Do not use volatile GType storage

---

meson.build
src/meson.build

With this change, graphene can be consumed as a subproject without
making any changes to the build files of a project. All you need to do
is provide a wrap file with a `[provide]` section:
https://mesonbuild.com/Wrap-dependency-system-manual.html#provide-section
This is also necessary because otherwise projects need to hard-code
the subproject name, which might be `graphene` when using `wrap-git` or
`graphene-1.10.8` when using `wrap-file` (to build from a release
tarball). This can cause conflicts between different subprojects that
consume graphene differently.
Other projects like glib, cairo, pango, etc already do this.
Also, stop using fallback: kwarg for deps that don't need it.

meson: Override dependencies to improve usage as a subproject

---

tests/meson.build

meson: don't install introspection file with installed_tests=false

---

doc/graphene-sections.txt
include/graphene-point.h
src/graphene-point.c
tests/point.c

A convenience function that computes the squared distance between two points, and avoids the per-axis components of distance().

Add squared distance operator for 2D points

---

meson.build

Environments that set up execution wrappers when cross-compiling should be allowed to run code. We only fall back on external properties if we really can't run any native code on the host machine.

build: Allow host builds when cross-compiling

---

src/meson.build

Build fails due to this issue if source path contains spaces.

build: Handle whitespaces in paths

---

doc/graphene-sections.txt
include/graphene-simd4f.h
src/graphene-simd4f.c
tests/simd.c

Use the naive implementation, unless we have access to SSE4.1 in which case we can use the native intrinsics.

Add rounding operators for graphene_simd4f_t

---

include/graphene-version-macros.h

The test is backward. (unfortunately, I spread that mistake in virgl too!)

Fix GRAPHENE_CHECK_VERSION

---

src/graphene-matrix.c
tests/matrix.c

Identity matrices are both 2D and 3D, and have well-known values, so it's better to have their own decomposition instead of going through the 2D and 3D decomposition code.
Fixes: #250

Add identity matrix decomposition

---

doc/graphene-sections.txt
include/graphene-box.h
src/graphene-box.c
tests/box.c

Similar to glibc's `sincos()`, it's easier to have a single call to initialise both vertices at the same time.

Add Box.get_minmax()

---

include/graphene-config.h.meson
include/graphene-simd4f.h
src/graphene-simd4f.c

AVX introduced a fast multiplication-addition intrinsic.

Add AVX implementation of graphene_simd4f_madd()
